default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: slp_contacts_development

test:
  <<: *default
  database: slp_contacts_test

production:
  <<: *default
  database: slp_contacts_production
